apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-petahhh
spec:
  title: Petahhh say's AYO
  description: Hello hello hello!
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: https://github.com/petahhh/lab-petahhh
  content:
    #image: quay.io/eduk8s/lab-markdown-sample:master
    files: github.com/petahhh/lab-petahhh
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
    env:
      - name: RESTART_URL
        value: https://neopets.com
      - name: WORKSHOP_FILE
        value: workshop-alternate.yaml
